# Site settings
title: datthinh1801
baseurl: "/About-Me/"
url: "https://datthinh1801.github.io/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Thinh Nguyen Dat
  desc: Hello nice to meet you
  email: datthinh1801@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: https://www.facebook.com/D477H1NH/
  flickr:
  github: datthinh1801
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/%C4%91%E1%BA%A1t-th%E1%BB%8Bnh-nguy%E1%BB%85n-97b141185/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: https://twitter.com/NguyntThnh19
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
